runtime: nodejs10

# We used F4 for the demo
instance_class: F1

env_variables:
  CLOUD_SQL_CONNECTION_NAME: "my-pet-project-285907:us-west2:my-pet-project-database"
  DB_USER: "root"
  DB_PASS: "jAkFyBxjpUYp4bGP"
  DB_NAME: "my_db"
